"""
ATLAS Theme Injection Module
============================
Injects CSS variables based on selected theme.
Part of MILESTONE-006: White-Label/Custom Branding

Author: EXECUTOR
Created: 2025-12-08

Usage:
    from app_themes import inject_theme_css, render_theme_selector
    
    # In sidebar
    theme_name = render_theme_selector()
    
    # After page config (before any content)
    inject_theme_css(theme_name)
"""

import streamlit as st
from typing import Optional
from config.themes import THEMES, get_theme, get_theme_names


def inject_theme_css(theme_name: str = 'atlas_dark') -> None:
    """
    Inject CSS variables for the selected theme.
    
    This overrides the default hardcoded colors with dynamic theme values.
    Must be called early in app startup, after st.set_page_config().
    
    Args:
        theme_name: Theme identifier from THEMES dict
    """
    theme = get_theme(theme_name)
    is_light = theme.get('mode') == 'light'
    
    css = f"""
    <style>
    /* ================================================================
       ATLAS THEME: {theme['name']}
       Mode: {theme.get('mode', 'dark')}
       Generated by app_themes.py
       ================================================================ */
    
    :root {{
        /* Core Colors */
        --primary: {theme['primary']};
        --primary-light: {theme['primary_light']};
        --primary-dark: {theme['primary_dark']};
        --secondary: {theme['secondary']};
        --secondary-light: {theme['secondary_light']};
        --accent: {theme['accent']};
        --highlight: {theme['highlight']};
        
        /* Background Colors */
        --bg-primary: {theme['background']};
        --bg-secondary: {theme['background_secondary']};
        --bg-card: {theme['card_bg']};
        --bg-card-alpha: {theme['card_bg_alpha']};
        --bg-hover: {theme['hover_bg']};
        
        /* Text Colors */
        --text-primary: {theme['text']};
        --text-secondary: {theme['text_secondary']};
        --text-muted: {theme['text_muted']};
        
        /* Border Colors */
        --border-subtle: {theme['border']};
        --border-accent: {theme['border_accent']};
        
        /* Status Colors */
        --success: {theme['success']};
        --warning: {theme['warning']};
        --danger: {theme['danger']};
        --info: {theme['info']};
        
        /* Gradient */
        --gradient: {theme['gradient']};
        
        /* Font */
        --font-family: {theme['font_family']};
    }}
    
    /* ================================================================
       BASE APP STYLING
       ================================================================ */
    
    .stApp {{
        background: var(--bg-primary) !important;
    }}
    
    [data-testid="stAppViewContainer"] {{
        background: var(--bg-primary) !important;
    }}
    
    [data-testid="stHeader"] {{
        background: {'rgba(248, 250, 252, 0.95)' if is_light else 'rgba(15, 20, 25, 0.95)'} !important;
        backdrop-filter: blur(10px);
    }}
    
    .main .block-container {{
        background: transparent !important;
    }}
    
    /* Global Font */
    * {{
        font-family: var(--font-family) !important;
    }}
    
    /* ================================================================
       SIDEBAR STYLING
       ================================================================ */
    
    [data-testid="stSidebar"] {{
        background: var(--bg-secondary) !important;
    }}
    
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] {{
        color: var(--text-primary) !important;
    }}
    
    [data-testid="stSidebar"] .stSelectbox label,
    [data-testid="stSidebar"] .stTextInput label {{
        color: var(--text-secondary) !important;
    }}
    
    /* ================================================================
       METRIC CARDS
       ================================================================ */
    
    .stMetric {{
        background: var(--bg-card) !important;
        padding: 1rem !important;
        border-radius: 10px !important;
        border: 1px solid var(--border-subtle) !important;
    }}
    
    .stMetric label {{
        color: var(--text-secondary) !important;
    }}
    
    [data-testid="stMetricValue"] {{
        color: var(--text-primary) !important;
    }}
    
    [data-testid="stMetricDelta"] svg {{
        fill: currentColor !important;
    }}
    
    /* Positive delta */
    [data-testid="stMetricDelta"][data-testid-delta="positive"] {{
        color: var(--success) !important;
    }}
    
    /* Negative delta */
    [data-testid="stMetricDelta"][data-testid-delta="negative"] {{
        color: var(--danger) !important;
    }}
    
    /* ================================================================
       TABS
       ================================================================ */
    
    .stTabs [data-baseweb="tab-list"] {{
        background: var(--bg-secondary) !important;
        border-radius: 10px !important;
        padding: 4px !important;
        gap: 4px !important;
    }}
    
    .stTabs [data-baseweb="tab"] {{
        color: var(--text-secondary) !important;
        background: transparent !important;
        border-radius: 8px !important;
    }}
    
    .stTabs [aria-selected="true"] {{
        background: var(--primary) !important;
        color: white !important;
    }}
    
    .stTabs [data-baseweb="tab-panel"] {{
        background: transparent !important;
    }}
    
    /* ================================================================
       EXPANDERS
       ================================================================ */
    
    .streamlit-expanderHeader {{
        background: var(--bg-card) !important;
        color: var(--text-primary) !important;
        border: 1px solid var(--border-subtle) !important;
        border-radius: 10px !important;
    }}
    
    .streamlit-expanderContent {{
        background: var(--bg-secondary) !important;
        border: 1px solid var(--border-subtle) !important;
        border-top: none !important;
        border-radius: 0 0 10px 10px !important;
    }}
    
    /* ================================================================
       BUTTONS
       ================================================================ */
    
    .stButton > button {{
        background: var(--gradient) !important;
        color: white !important;
        border: none !important;
        border-radius: 10px !important;
        font-weight: 600 !important;
        transition: all 0.3s ease !important;
    }}
    
    .stButton > button:hover {{
        transform: translateY(-2px) !important;
        box-shadow: 0 4px 15px rgba(0,0,0,0.3) !important;
    }}
    
    /* Secondary buttons */
    .stButton > button[kind="secondary"] {{
        background: var(--bg-card) !important;
        color: var(--text-primary) !important;
        border: 1px solid var(--border-accent) !important;
    }}
    
    /* ================================================================
       INPUTS
       ================================================================ */
    
    .stTextInput > div > div > input,
    .stSelectbox > div > div,
    .stMultiSelect > div > div {{
        background: var(--bg-card) !important;
        color: var(--text-primary) !important;
        border: 1px solid var(--border-subtle) !important;
        border-radius: 8px !important;
    }}
    
    .stTextInput > div > div > input:focus {{
        border-color: var(--primary) !important;
        box-shadow: 0 0 0 2px var(--border-accent) !important;
    }}
    
    /* ================================================================
       DATAFRAMES / TABLES
       ================================================================ */
    
    .stDataFrame {{
        background: var(--bg-card) !important;
        border-radius: 10px !important;
        overflow: hidden !important;
    }}
    
    .stDataFrame [data-testid="stDataFrameResizable"] {{
        background: var(--bg-card) !important;
    }}
    
    /* ================================================================
       ALERTS / INFO BOXES
       ================================================================ */
    
    .stAlert {{
        border-radius: 10px !important;
    }}
    
    [data-testid="stAlert"][kind="info"] {{
        background: rgba(59, 130, 246, 0.1) !important;
        border-left-color: var(--info) !important;
    }}
    
    [data-testid="stAlert"][kind="success"] {{
        background: rgba(16, 185, 129, 0.1) !important;
        border-left-color: var(--success) !important;
    }}
    
    [data-testid="stAlert"][kind="warning"] {{
        background: rgba(245, 158, 11, 0.1) !important;
        border-left-color: var(--warning) !important;
    }}
    
    [data-testid="stAlert"][kind="error"] {{
        background: rgba(239, 68, 68, 0.1) !important;
        border-left-color: var(--danger) !important;
    }}
    
    /* ================================================================
       CUSTOM CLASSES (metric-card, flip-card, etc.)
       ================================================================ */
    
    .metric-card {{
        background: var(--bg-card) !important;
        border: 1px solid var(--border-subtle) !important;
        color: var(--text-primary) !important;
    }}
    
    .metric-card:hover {{
        background: var(--bg-hover) !important;
        border-color: var(--border-accent) !important;
    }}
    
    .metric-label {{
        color: var(--text-secondary) !important;
    }}
    
    .metric-value {{
        color: var(--text-primary) !important;
    }}
    
    .metric-value.positive {{
        color: var(--success) !important;
    }}
    
    .metric-value.negative {{
        color: var(--danger) !important;
    }}
    
    /* ================================================================
       CHARTS / PLOTLY
       ================================================================ */
    
    .js-plotly-plot .plotly .modebar {{
        background: var(--bg-card) !important;
    }}
    
    .js-plotly-plot .plotly .modebar-btn {{
        color: var(--text-secondary) !important;
    }}
    
    /* ================================================================
       SCROLLBAR (Dark/Light aware)
       ================================================================ */
    
    ::-webkit-scrollbar {{
        width: 8px;
        height: 8px;
    }}
    
    ::-webkit-scrollbar-track {{
        background: var(--bg-secondary);
    }}
    
    ::-webkit-scrollbar-thumb {{
        background: var(--border-accent);
        border-radius: 4px;
    }}
    
    ::-webkit-scrollbar-thumb:hover {{
        background: var(--primary);
    }}
    
    /* ================================================================
       MAIN HEADER
       ================================================================ */
    
    .main-header {{
        color: var(--text-primary) !important;
        text-shadow: 0 0 30px {'rgba(37, 99, 235, 0.3)' if is_light else 'rgba(59, 130, 246, 0.5)'}, 
                     0 2px 4px rgba(0, 0, 0, {'0.1' if is_light else '0.5'});
    }}
    
    /* ================================================================
       LIGHT MODE SPECIFIC OVERRIDES
       ================================================================ */
    
    {'/* Light mode active */' if is_light else '/* Dark mode active */'}
    
    {'''
    /* Light mode shadow adjustments */
    .metric-card {
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08) !important;
    }
    
    .stButton > button {
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1) !important;
    }
    
    /* Ensure links are visible in light mode */
    a {
        color: var(--primary) !important;
    }
    ''' if is_light else ''}
    
    </style>
    """
    
    st.markdown(css, unsafe_allow_html=True)


def render_theme_selector(
    position: str = 'sidebar',
    key: str = 'theme_selector'
) -> str:
    """
    Render theme selector dropdown.
    
    Args:
        position: 'sidebar' or 'main' 
        key: Unique key for the widget
        
    Returns:
        Selected theme name
    """
    theme_options = get_theme_names()
    
    # Get current theme from session state or default
    if 'current_theme' not in st.session_state:
        st.session_state.current_theme = 'atlas_dark'
    
    # Store the PREVIOUS theme to detect changes
    previous_theme = st.session_state.current_theme
    
    # Determine current index
    theme_keys = list(theme_options.keys())
    try:
        current_index = theme_keys.index(st.session_state.current_theme)
    except ValueError:
        current_index = 0
    
    # Render in appropriate location
    if position == 'sidebar':
        selected_name = st.sidebar.selectbox(
            "🎨 Theme",
            options=theme_keys,
            format_func=lambda x: theme_options[x],
            index=current_index,
            key=key,
            help="Switch color theme"
        )
    else:
        selected_name = st.selectbox(
            "🎨 Theme",
            options=theme_keys,
            format_func=lambda x: theme_options[x],
            index=current_index,
            key=key,
            help="Switch color theme"
        )
    
    # Update session state BEFORE potential rerun
    st.session_state.current_theme = selected_name
    
    # CRITICAL FIX: Trigger rerun if theme changed to apply immediately
    if selected_name != previous_theme:
        st.rerun()
    
    return selected_name


def get_current_theme() -> str:
    """Get currently selected theme from session state."""
    return st.session_state.get('current_theme', 'atlas_dark')


def get_theme_mode() -> str:
    """Get current theme mode (light/dark)."""
    theme = get_theme(get_current_theme())
    return theme.get('mode', 'dark')


def is_light_mode() -> bool:
    """Check if current theme is light mode."""
    return get_theme_mode() == 'light'


# =============================================================================
# CONVENIENCE: Get theme-aware colors for Plotly/Matplotlib
# =============================================================================

def get_chart_colors() -> dict:
    """
    Get color palette for charts based on current theme.
    
    Returns:
        Dict with keys: background, text, primary, secondary, success, danger
    """
    theme = get_theme(get_current_theme())
    
    return {
        'background': theme['background'],
        'paper_bg': theme['card_bg'],
        'text': theme['text'],
        'text_secondary': theme['text_secondary'],
        'primary': theme['primary'],
        'secondary': theme['secondary'],
        'success': theme['success'],
        'danger': theme['danger'],
        'warning': theme['warning'],
        'grid': theme['border'],
    }


def get_plotly_template() -> str:
    """Get Plotly template name based on current theme mode."""
    return 'plotly_white' if is_light_mode() else 'plotly_dark'

