"""
S&P 500 Tickers List
Current as of November 2025
"""

SP500_TICKERS = [
    "A", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI",
    "ADM", "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG",
    "AKAM", "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AMD", "AME", "AMGN",
    "AMP", "AMT", "AMZN", "ANET", "ANSS", "AON", "AOS", "APA", "APD", "APH",
    "APTV", "ARE", "ATO", "AVB", "AVGO", "AVY", "AWK", "AXON", "AXP", "AZO",
    "BA", "BAC", "BALL", "BAX", "BBWI", "BBY", "BDX", "BEN", "BF.B", "BKNG",
    "BKR", "BLDR", "BLK", "BMY", "BR", "BRO", "BSX", "BWA", "BX", "BXP",
    "C", "CAG", "CAH", "CARR", "CAT", "CB", "CBOE", "CBRE", "CCI", "CCL",
    "CDNS", "CDW", "CE", "CEG", "CF", "CFG", "CHD", "CHRW", "CHTR", "CI",
    "CINF", "CL", "CLX", "CMCSA", "CME", "CMG", "CMI", "CMS", "CNC", "CNP",
    "COF", "COO", "COP", "COR", "COST", "CPAY", "CPB", "CPRT", "CPT", "CRL",
    "CRM", "CSCO", "CSGP", "CSX", "CTAS", "CTLT", "CTRA", "CTSH", "CTVA", "CVS",
    "CVX", "CZR", "D", "DAL", "DAY", "DD", "DE", "DECK", "DFS", "DG",
    "DGX", "DHI", "DHR", "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ",
    "DRI", "DTE", "DUK", "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED",
    "EFX", "EG", "EIX", "EL", "ELV", "EMN", "EMR", "ENPH", "EOG", "EPAM",
    "EQIX", "EQR", "EQT", "ES", "ESS", "ETN", "ETR", "ETSY", "EVRG", "EW",
    "EXC", "EXPD", "EXPE", "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX",
    "FE", "FFIV", "FI", "FICO", "FIS", "FITB", "FMC", "FOX", "FOXA", "FRT",
    "FSLR", "FTNT", "FTV", "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD",
    "GIS", "GL", "GLW", "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN",
    "GS", "GWW", "HAL", "HAS", "HBAN", "HCA", "HD", "HES", "HIG", "HII",
    "HLT", "HOLX", "HON", "HPE", "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB",
    "HUM", "HWM", "IBM", "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU",
    "INVH", "IP", "IPG", "IQV", "IR", "IRM", "ISRG", "IT", "ITW", "IVZ",
    "J", "JBHT", "JBL", "JCI", "JKHY", "JNJ", "JNPR", "JPM", "K", "KDP",
    "KEY", "KEYS", "KHC", "KIM", "KKR", "KLAC", "KMB", "KMI", "KMX", "KO",
    "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX", "LIN", "LKQ", "LLY",
    "LMT", "LNT", "LOGI", "LOW", "LRCX", "LULU", "LUV", "LVS", "LW", "LYB",
    "LYV", "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK", "MCO", "MDLZ",
    "MDT", "MET", "META", "MGM", "MHK", "MKC", "MKTX", "MLM", "MMC", "MMM",
    "MNST", "MO", "MOH", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MRO", "MS",
    "MSCI", "MSFT", "MSI", "MTB", "MTCH", "MTD", "MU", "NCLH", "NDAQ", "NDSN",
    "NEE", "NEM", "NFLX", "NI", "NKE", "NOC", "NOW", "NRG", "NSC", "NTAP",
    "NTRS", "NUE", "NVDA", "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL", "OKE",
    "OMC", "ON", "ORCL", "ORLY", "OTIS", "OXY", "PANW", "PARA", "PAYC", "PAYX",
    "PCAR", "PCG", "PEG", "PEP", "PFE", "PFG", "PG", "PGR", "PH", "PHM",
    "PKG", "PLD", "PM", "PNC", "PNR", "PNW", "PODD", "POOL", "PPG", "PPL",
    "PRU", "PSA", "PSX", "PTC", "PWR", "PYPL", "QCOM", "QRVO", "RCL", "REG",
    "REGN", "RF", "RJF", "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG",
    "RTX", "RVTY", "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA",
    "SNPS", "SO", "SPG", "SPGI", "SRE", "STE", "STLD", "STT", "STX", "STZ",
    "SWK", "SWKS", "SYF", "SYK", "SYY", "T", "TAP", "TDG", "TDY", "TECH",
    "TEL", "TER", "TFC", "TFX", "TGT", "TJX", "TMO", "TMUS", "TPR", "TRGP",
    "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTWO", "TXN", "TXT",
    "TYL", "UAL", "UBER", "UDR", "UHS", "ULTA", "UNH", "UNP", "UPS", "URI",
    "USB", "V", "VICI", "VLO", "VLTO", "VMC", "VRSK", "VRSN", "VRTX", "VST",
    "VTR", "VTRS", "VZ", "WAB", "WAT", "WBA", "WBD", "WDC", "WEC", "WELL",
    "WFC", "WM", "WMB", "WMT", "WRB", "WRK", "WST", "WTW", "WY", "WYNN",
    "XEL", "XOM", "XYL", "YUM", "ZBH", "ZBRA", "ZTS"
]

# Total: 503 tickers (S&P 500 + a few multi-class shares)

# S&P 500 Company Names Mapping
SP500_COMPANIES = {
    "A": "Agilent Technologies", "AAL": "American Airlines", "AAPL": "Apple Inc.", "ABBV": "AbbVie Inc.",
    "ABNB": "Airbnb Inc.", "ABT": "Abbott Laboratories", "ACGL": "Arch Capital Group", "ACN": "Accenture",
    "ADBE": "Adobe Inc.", "ADI": "Analog Devices", "ADM": "Archer-Daniels-Midland", "ADP": "Automatic Data Processing",
    "ADSK": "Autodesk Inc.", "AEE": "Ameren Corp.", "AEP": "American Electric Power", "AES": "AES Corp.",
    "AFL": "Aflac Inc.", "AIG": "American International Group", "AIZ": "Assurant Inc.", "AJG": "Arthur J. Gallagher",
    "AKAM": "Akamai Technologies", "ALB": "Albemarle Corp.", "ALGN": "Align Technology", "ALL": "Allstate Corp.",
    "ALLE": "Allegion PLC", "AMAT": "Applied Materials", "AMCR": "Amcor PLC", "AMD": "Advanced Micro Devices",
    "AME": "AMETEK Inc.", "AMGN": "Amgen Inc.", "AMP": "Ameriprise Financial", "AMT": "American Tower",
    "AMZN": "Amazon.com Inc.", "ANET": "Arista Networks", "ANSS": "ANSYS Inc.", "AON": "Aon PLC",
    "AOS": "A. O. Smith", "APA": "APA Corp.", "APD": "Air Products & Chemicals", "APH": "Amphenol Corp.",
    "APTV": "Aptiv PLC", "ARE": "Alexandria Real Estate", "ATO": "Atmos Energy", "AVB": "AvalonBay Communities",
    "AVGO": "Broadcom Inc.", "AVY": "Avery Dennison", "AWK": "American Water Works", "AXON": "Axon Enterprise",
    "AXP": "American Express", "AZO": "AutoZone Inc.", "BA": "Boeing Co.", "BAC": "Bank of America",
    "BALL": "Ball Corp.", "BAX": "Baxter International", "BBWI": "Bath & Body Works", "BBY": "Best Buy",
    "BDX": "Becton Dickinson", "BEN": "Franklin Resources", "BF.B": "Brown-Forman Corp.", "BKNG": "Booking Holdings",
    "BKR": "Baker Hughes", "BLDR": "Builders FirstSource", "BLK": "BlackRock Inc.", "BMY": "Bristol Myers Squibb",
    "BR": "Broadridge Financial", "BRO": "Brown & Brown", "BSX": "Boston Scientific", "BWA": "BorgWarner Inc.",
    "BX": "Blackstone Inc.", "BXP": "Boston Properties", "C": "Citigroup Inc.", "CAG": "Conagra Brands",
    "CAH": "Cardinal Health", "CARR": "Carrier Global", "CAT": "Caterpillar Inc.", "CB": "Chubb Ltd.",
    "CBOE": "Cboe Global Markets", "CBRE": "CBRE Group", "CCI": "Crown Castle", "CCL": "Carnival Corp.",
    "CDNS": "Cadence Design Systems", "CDW": "CDW Corp.", "CE": "Celanese Corp.", "CEG": "Constellation Energy",
    "CF": "CF Industries", "CFG": "Citizens Financial", "CHD": "Church & Dwight", "CHRW": "C.H. Robinson",
    "CHTR": "Charter Communications", "CI": "Cigna Group", "CINF": "Cincinnati Financial", "CL": "Colgate-Palmolive",
    "CLX": "Clorox Co.", "CMCSA": "Comcast Corp.", "CME": "CME Group", "CMG": "Chipotle Mexican Grill",
    "CMI": "Cummins Inc.", "CMS": "CMS Energy", "CNC": "Centene Corp.", "CNP": "CenterPoint Energy",
    "COF": "Capital One Financial", "COO": "Cooper Companies", "COP": "ConocoPhillips", "COR": "Cencora Inc.",
    "COST": "Costco Wholesale", "CPAY": "Corpay Inc.", "CPB": "Campbell Soup", "CPRT": "Copart Inc.",
    "CPT": "Camden Property Trust", "CRL": "Charles River Labs", "CRM": "Salesforce Inc.", "CSCO": "Cisco Systems",
    "CSGP": "CoStar Group", "CSX": "CSX Corp.", "CTAS": "Cintas Corp.", "CTLT": "Catalent Inc.",
    "CTRA": "Coterra Energy", "CTSH": "Cognizant Technology", "CTVA": "Corteva Inc.", "CVS": "CVS Health",
    "CVX": "Chevron Corp.", "CZR": "Caesars Entertainment", "D": "Dominion Energy", "DAL": "Delta Air Lines",
    "DAY": "Dayforce Inc.", "DD": "DuPont de Nemours", "DE": "Deere & Co.", "DECK": "Deckers Outdoor",
    "DFS": "Discover Financial", "DG": "Dollar General", "DGX": "Quest Diagnostics", "DHI": "D.R. Horton",
    "DHR": "Danaher Corp.", "DIS": "Walt Disney Co.", "DLR": "Digital Realty Trust", "DLTR": "Dollar Tree",
    "DOC": "Healthpeak Properties", "DOV": "Dover Corp.", "DOW": "Dow Inc.", "DPZ": "Domino's Pizza",
    "DRI": "Darden Restaurants", "DTE": "DTE Energy", "DUK": "Duke Energy", "DVA": "DaVita Inc.",
    "DVN": "Devon Energy", "DXCM": "DexCom Inc.", "EA": "Electronic Arts", "EBAY": "eBay Inc.",
    "ECL": "Ecolab Inc.", "ED": "Consolidated Edison", "EFX": "Equifax Inc.", "EG": "Everest Group",
    "EIX": "Edison International", "EL": "Estée Lauder", "ELV": "Elevance Health", "EMN": "Eastman Chemical",
    "EMR": "Emerson Electric", "ENPH": "Enphase Energy", "EOG": "EOG Resources", "EPAM": "EPAM Systems",
    "EQIX": "Equinix Inc.", "EQR": "Equity Residential", "EQT": "EQT Corp.", "ES": "Eversource Energy",
    "ESS": "Essex Property Trust", "ETN": "Eaton Corp.", "ETR": "Entergy Corp.", "ETSY": "Etsy Inc.",
    "EVRG": "Evergy Inc.", "EW": "Edwards Lifesciences", "EXC": "Exelon Corp.", "EXPD": "Expeditors International",
    "EXPE": "Expedia Group", "EXR": "Extra Space Storage", "F": "Ford Motor Co.", "FANG": "Diamondback Energy",
    "FAST": "Fastenal Co.", "FCX": "Freeport-McMoRan", "FDS": "FactSet Research", "FDX": "FedEx Corp.",
    "FE": "FirstEnergy Corp.", "FFIV": "F5 Inc.", "FI": "Fiserv Inc.", "FICO": "Fair Isaac Corp.",
    "FIS": "Fidelity National Information", "FITB": "Fifth Third Bancorp", "FMC": "FMC Corp.", "FOX": "Fox Corp. Class B",
    "FOXA": "Fox Corp. Class A", "FRT": "Federal Realty Investment", "FSLR": "First Solar", "FTNT": "Fortinet Inc.",
    "FTV": "Fortive Corp.", "GD": "General Dynamics", "GDDY": "GoDaddy Inc.", "GE": "General Electric",
    "GEHC": "GE HealthCare", "GEN": "Gen Digital", "GEV": "GE Vernova", "GILD": "Gilead Sciences",
    "GIS": "General Mills", "GL": "Globe Life", "GLW": "Corning Inc.", "GM": "General Motors",
    "GNRC": "Generac Holdings", "GOOG": "Alphabet Inc. Class C", "GOOGL": "Alphabet Inc. Class A", "GPC": "Genuine Parts",
    "GPN": "Global Payments", "GRMN": "Garmin Ltd.", "GS": "Goldman Sachs", "GWW": "W.W. Grainger",
    "HAL": "Halliburton Co.", "HAS": "Hasbro Inc.", "HBAN": "Huntington Bancshares", "HCA": "HCA Healthcare",
    "HD": "Home Depot", "HES": "Hess Corp.", "HIG": "Hartford Financial", "HII": "Huntington Ingalls",
    "HLT": "Hilton Worldwide", "HOLX": "Hologic Inc.", "HON": "Honeywell International", "HPE": "Hewlett Packard Enterprise",
    "HPQ": "HP Inc.", "HRL": "Hormel Foods", "HSIC": "Henry Schein", "HST": "Host Hotels & Resorts",
    "HSY": "Hershey Co.", "HUBB": "Hubbell Inc.", "HUM": "Humana Inc.", "HWM": "Howmet Aerospace",
    "IBM": "IBM Corp.", "ICE": "Intercontinental Exchange", "IDXX": "IDEXX Laboratories", "IEX": "IDEX Corp.",
    "IFF": "International Flavors & Fragrances", "INCY": "Incyte Corp.", "INTC": "Intel Corp.", "INTU": "Intuit Inc.",
    "INVH": "Invitation Homes", "IP": "International Paper", "IPG": "Interpublic Group", "IQV": "IQVIA Holdings",
    "IR": "Ingersoll Rand", "IRM": "Iron Mountain", "ISRG": "Intuitive Surgical", "IT": "Gartner Inc.",
    "ITW": "Illinois Tool Works", "IVZ": "Invesco Ltd.", "J": "Jacobs Solutions", "JBHT": "J.B. Hunt Transport",
    "JBL": "Jabil Inc.", "JCI": "Johnson Controls", "JKHY": "Jack Henry & Associates", "JNJ": "Johnson & Johnson",
    "JNPR": "Juniper Networks", "JPM": "JPMorgan Chase", "K": "Kellanova", "KDP": "Keurig Dr Pepper",
    "KEY": "KeyCorp", "KEYS": "Keysight Technologies", "KHC": "Kraft Heinz", "KIM": "Kimco Realty",
    "KKR": "KKR & Co.", "KLAC": "KLA Corp.", "KMB": "Kimberly-Clark", "KMI": "Kinder Morgan",
    "KMX": "CarMax Inc.", "KO": "Coca-Cola Co.", "KR": "Kroger Co.", "KVUE": "Kenvue Inc.",
    "L": "Loews Corp.", "LDOS": "Leidos Holdings", "LEN": "Lennar Corp.", "LH": "Labcorp Holdings",
    "LHX": "L3Harris Technologies", "LIN": "Linde PLC", "LKQ": "LKQ Corp.", "LLY": "Eli Lilly",
    "LMT": "Lockheed Martin", "LNT": "Alliant Energy", "LOGI": "Logitech International", "LOW": "Lowe's Companies",
    "LRCX": "Lam Research", "LULU": "Lululemon Athletica", "LUV": "Southwest Airlines", "LVS": "Las Vegas Sands",
    "LW": "Lamb Weston", "LYB": "LyondellBasell", "LYV": "Live Nation Entertainment", "MA": "Mastercard Inc.",
    "MAA": "Mid-America Apartment", "MAR": "Marriott International", "MAS": "Masco Corp.", "MCD": "McDonald's Corp.",
    "MCHP": "Microchip Technology", "MCK": "McKesson Corp.", "MCO": "Moody's Corp.", "MDLZ": "Mondelez International",
    "MDT": "Medtronic PLC", "MET": "MetLife Inc.", "META": "Meta Platforms", "MGM": "MGM Resorts",
    "MHK": "Mohawk Industries", "MKC": "McCormick & Co.", "MKTX": "MarketAxess Holdings", "MLM": "Martin Marietta Materials",
    "MMC": "Marsh & McLennan", "MMM": "3M Co.", "MNST": "Monster Beverage", "MO": "Altria Group",
    "MOH": "Molina Healthcare", "MOS": "Mosaic Co.", "MPC": "Marathon Petroleum", "MPWR": "Monolithic Power Systems",
    "MRK": "Merck & Co.", "MRNA": "Moderna Inc.", "MRO": "Marathon Oil", "MS": "Morgan Stanley",
    "MSCI": "MSCI Inc.", "MSFT": "Microsoft Corp.", "MSI": "Motorola Solutions", "MTB": "M&T Bank",
    "MTCH": "Match Group", "MTD": "Mettler-Toledo", "MU": "Micron Technology", "NCLH": "Norwegian Cruise Line",
    "NDAQ": "Nasdaq Inc.", "NDSN": "Nordson Corp.", "NEE": "NextEra Energy", "NEM": "Newmont Corp.",
    "NFLX": "Netflix Inc.", "NI": "NiSource Inc.", "NKE": "Nike Inc.", "NOC": "Northrop Grumman",
    "NOW": "ServiceNow Inc.", "NRG": "NRG Energy", "NSC": "Norfolk Southern", "NTAP": "NetApp Inc.",
    "NTRS": "Northern Trust", "NUE": "Nucor Corp.", "NVDA": "NVIDIA Corp.", "NVR": "NVR Inc.",
    "NWS": "News Corp Class B", "NWSA": "News Corp Class A", "NXPI": "NXP Semiconductors", "O": "Realty Income",
    "ODFL": "Old Dominion Freight", "OKE": "ONEOK Inc.", "OMC": "Omnicom Group", "ON": "ON Semiconductor",
    "ORCL": "Oracle Corp.", "ORLY": "O'Reilly Automotive", "OTIS": "Otis Worldwide", "OXY": "Occidental Petroleum",
    "PANW": "Palo Alto Networks", "PARA": "Paramount Global", "PAYC": "Paycom Software", "PAYX": "Paychex Inc.",
    "PCAR": "PACCAR Inc.", "PCG": "PG&E Corp.", "PEG": "Public Service Enterprise", "PEP": "PepsiCo Inc.",
    "PFE": "Pfizer Inc.", "PFG": "Principal Financial", "PG": "Procter & Gamble", "PGR": "Progressive Corp.",
    "PH": "Parker-Hannifin", "PHM": "PulteGroup Inc.", "PKG": "Packaging Corp of America", "PLD": "Prologis Inc.",
    "PM": "Philip Morris International", "PNC": "PNC Financial", "PNR": "Pentair PLC", "PNW": "Pinnacle West Capital",
    "PODD": "Insulet Corp.", "POOL": "Pool Corp.", "PPG": "PPG Industries", "PPL": "PPL Corp.",
    "PRU": "Prudential Financial", "PSA": "Public Storage", "PSX": "Phillips 66", "PTC": "PTC Inc.",
    "PWR": "Quanta Services", "PYPL": "PayPal Holdings", "QCOM": "Qualcomm Inc.", "QRVO": "Qorvo Inc.",
    "RCL": "Royal Caribbean", "REG": "Regency Centers", "REGN": "Regeneron Pharmaceuticals", "RF": "Regions Financial",
    "RJF": "Raymond James Financial", "RL": "Ralph Lauren", "RMD": "ResMed Inc.", "ROK": "Rockwell Automation",
    "ROL": "Rollins Inc.", "ROP": "Roper Technologies", "ROST": "Ross Stores", "RSG": "Republic Services",
    "RTX": "RTX Corp.", "RVTY": "Revvity Inc.", "SBAC": "SBA Communications", "SBUX": "Starbucks Corp.",
    "SCHW": "Charles Schwab", "SHW": "Sherwin-Williams", "SJM": "J.M. Smucker", "SLB": "Schlumberger Ltd.",
    "SMCI": "Super Micro Computer", "SNA": "Snap-on Inc.", "SNPS": "Synopsys Inc.", "SO": "Southern Co.",
    "SPG": "Simon Property Group", "SPGI": "S&P Global", "SRE": "Sempra", "STE": "STERIS PLC",
    "STLD": "Steel Dynamics", "STT": "State Street", "STX": "Seagate Technology", "STZ": "Constellation Brands",
    "SWK": "Stanley Black & Decker", "SWKS": "Skyworks Solutions", "SYF": "Synchrony Financial", "SYK": "Stryker Corp.",
    "SYY": "Sysco Corp.", "T": "AT&T Inc.", "TAP": "Molson Coors Brewing", "TDG": "TransDigm Group",
    "TDY": "Teledyne Technologies", "TECH": "Bio-Techne Corp.", "TEL": "TE Connectivity", "TER": "Teradyne Inc.",
    "TFC": "Truist Financial", "TFX": "Teleflex Inc.", "TGT": "Target Corp.", "TJX": "TJX Companies",
    "TMO": "Thermo Fisher Scientific", "TMUS": "T-Mobile US", "TPR": "Tapestry Inc.", "TRGP": "Targa Resources",
    "TRMB": "Trimble Inc.", "TROW": "T. Rowe Price", "TRV": "Travelers Companies", "TSCO": "Tractor Supply",
    "TSLA": "Tesla Inc.", "TSN": "Tyson Foods", "TT": "Trane Technologies", "TTWO": "Take-Two Interactive",
    "TXN": "Texas Instruments", "TXT": "Textron Inc.", "TYL": "Tyler Technologies", "UAL": "United Airlines",
    "UBER": "Uber Technologies", "UDR": "UDR Inc.", "UHS": "Universal Health Services", "ULTA": "Ulta Beauty",
    "UNH": "UnitedHealth Group", "UNP": "Union Pacific", "UPS": "United Parcel Service", "URI": "United Rentals",
    "USB": "U.S. Bancorp", "V": "Visa Inc.", "VICI": "VICI Properties", "VLO": "Valero Energy",
    "VLTO": "Veralto Corp.", "VMC": "Vulcan Materials", "VRSK": "Verisk Analytics", "VRSN": "VeriSign Inc.",
    "VRTX": "Vertex Pharmaceuticals", "VST": "Vistra Corp.", "VTR": "Ventas Inc.", "VTRS": "Viatris Inc.",
    "VZ": "Verizon Communications", "WAB": "Westinghouse Air Brake", "WAT": "Waters Corp.", "WBA": "Walgreens Boots Alliance",
    "WBD": "Warner Bros. Discovery", "WDC": "Western Digital", "WEC": "WEC Energy Group", "WELL": "Welltower Inc.",
    "WFC": "Wells Fargo", "WM": "Waste Management", "WMB": "Williams Companies", "WMT": "Walmart Inc.",
    "WRB": "W. R. Berkley", "WRK": "WestRock Co.", "WST": "West Pharmaceutical", "WTW": "Willis Towers Watson",
    "WY": "Weyerhaeuser Co.", "WYNN": "Wynn Resorts", "XEL": "Xcel Energy", "XOM": "Exxon Mobil",
    "XYL": "Xylem Inc.", "YUM": "Yum! Brands", "ZBH": "Zimmer Biomet", "ZBRA": "Zebra Technologies",
    "ZTS": "Zoetis Inc."
}

# Create display list: "Company Name (TICKER)" sorted alphabetically by company name
SP500_DISPLAY = ["--"] + [f"{name} ({ticker})" for ticker, name in sorted(SP500_COMPANIES.items(), key=lambda x: x[1])]

def extract_ticker(display_string: str) -> str:
    """
    Extract ticker from 'Company Name (TICKER)' format
    
    Args:
        display_string: String in format "Company Name (TICKER)"
        
    Returns:
        Ticker symbol or empty string
    """
    if display_string == "--":
        return ""
    # Extract text between parentheses
    import re
    match = re.search(r'\(([^)]+)\)$', display_string)
    return match.group(1) if match else ""

